---
title: "MTG Collection"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
    source_code: embed
---

```{r setup, include=FALSE}
library(flexdashboard)
library(knitr)
library(DT)
library(rpivotTable)
library(ggplot2)
library(openintro)
library(highcharter)
library(dplyr)
library(tidyverse)
library(plotly)
library(maps)
library(httr)
library(jsonlite)



```

```{r}
data <- read.csv("~/Documents/GitHub/mtg/data.csv")

collection <- data %>% select('Count','Name', 'Edition','Card.Number') %>%
  mutate(Edition = replace(Edition, Edition == 'Secret Lair Drop Series', 'Secret Lair Drop'))

collection <- setNames(collection, c('count','name','edition','cardNumber')) 

Scryfall <- read.csv("~/Documents/GitHub/mtg/Scryfall.csv")
Scryfall <- Scryfall %>% select('Name','Edition','Set','Card.Number','tcgplayer_id') 

```




```{r}

```

```{r}


```


Home
==================

Row
------------------

### Data Refreshed August 11, 2021

```{r}
valueBox(paste('Marcin MTG Data'),
color = '#063970')
```

### Count of Cards

```{r}

valueBox(length(collection$name),
         icon = 'fa-tree')

```


Full Collection Table
========================
```{r}

dataSummary <- data %>% select('Name','Edition','Card.Number','Count') %>%
  mutate(Edition = replace(Edition, Edition == 'Secret Lair Drop Series', 'Secret Lair Drop')) 

test <- as.numeric(dataSummary$Card.Number)

dataSummary <- left_join(dataSummary, Scryfall, by = c('Edition','Name','Card.Number'))
dataSummary <- setNames(dataSummary, c('Name','Set','Card Number','Count','TCGPlayer Id','Set Id'))


datatable(dataSummary,
          caption = 'Full Collection Table',
          rownames = T,
          filter = 'top',
          options= list(pageLength = 100))


write.csv(dataSummary,"~/Documents/GitHub/mtg/marcin-inventory.csv", row.names = TRUE)


```









